name = "cf-torrent"
main = ".svelte-kit/cloudflare/_worker.js"

workers_dev = true
compatibility_date = "2024-09-23"

compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
